# Generated by Django 5.0.4 on 2024-05-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesoracle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.RemoveField(
            model_name='business',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='success_score',
        ),
        migrations.AddField(
            model_name='business',
            name='revenue_t0',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='business',
            name='revenue_t1',
            field=models.FloatField(default=0.0, verbose_name='Revenue at Time 1'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='growth_percentage',
            field=models.FloatField(default=0.0, verbose_name='Growth Percentage'),
        ),
    ]
