# Generated by Django 5.0.4 on 2024-05-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesoracle', '0002_remove_business_industry_remove_business_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='revenue_t0',
            new_name='revenue',
        ),
        migrations.RemoveField(
            model_name='business',
            name='revenue_t1',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
    ]
